#!/bin/bash

cwd=`pwd`
if [ -e setenv ]; then source setenv; else ./setenv.sh; source setenv; fi

if [ ! ${1} ] || [ ! ${2} ] || [ ! ${3} ] || [ ! ${4} ] || [ ! ${5} ] || [ ! ${6} ]; then
    printf "\n>>> Usage: ./run <drude/c36> <resid> <atom1> <atom2> <atom3> <atom4>\n"
    printf "\ne.g. ./run drude bglcna o5 c1 c2 c3\n"
    printf "\nNeeds psf and crd files named: <resid>.<c36/drude>.psf & <resid>.<c36/drude>.crd\n\n"
    exit
fi

mkdir -p output
resid="${2}"
a1="${3}"
a2="${4}"
a3="${5}"
a4="${6}"
mkdir -p output/${resid}_dihe_${a1}_${a2}_${a3}_${a4}

printf "\n>>> Generating coordinates..."

$CHARMMDIR/charmm -i generate_coordinates.inp method=$1 resid=$resid a1=$a1 a2=$a2 a3=$a3 a4=$a4 > generate_coordinates.out
flag=`tail -n 6 generate_coordinates.out | head -n 1 | awk '{print $1}'`
if [ $flag == "ABNORMAL" ]; then
    printf " failed! Check generate_coordinates.out for errors! \n"
    exit
else
    printf " success!\n"
    sort -n fort.11 > output/mm_${resid}_dihe_${a1}_${a2}_${a3}_${a4}.txt
    rm fort.11
fi

printf "\n>>> Removing high energy conformations..."
$PYTHONDIR/python process_mme.py $resid $a1 $a2 $a3 $a4 > process_mme.out
if [ -e output/${resid}_dihe_${a1}_${a2}_${a3}_${a4}.mme ]; then
    printf " success!\n"
else
    printf " failed! Check process_mme.out for errors! \n"
    exit
fi

printf "\n>>> Generating psi4 inputs..."
cd output/${resid}_dihe_${a1}_${a2}_${a3}_${a4}
for i in *psi4.pdb; do
    printf " ${i:2:4}..."
    $PYTHONDIR/python ../../get_psi4_input.py $i $a1 $a2 $a3 $a4 > ${i:0:(-4)}.inp
done
printf " Done!\n\n"


